#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "optparse"
require_relative "../lib/e2e_matrix_to_browserstack_run_plan"
require_relative "../../scripts/lib/cli_output"

options = {
  config: File.expand_path("../config/matrix.yml", __dir__)
}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: e2e/scripts/e2e_matrix_to_browserstack_run_plan validate|expand|application|count|bitrise-env|assert-pipeline-coverage [options]"
  opts.on("--config PATH") { |path| options[:config] = path }
  opts.on("--index INDEX", Integer) { |index| options[:index] = index }
  opts.on("--application ID") { |application| options[:application] = application }
  opts.on("--changed-files-file PATH") { |path| options[:changed_files_file] = path }
  opts.on("--changed-file PATH") { |path| (options[:changed_files] ||= []) << path }
  opts.on("--pipeline-config PATH") { |path| options[:pipeline_config] = path }
end

command = ARGV.shift
parser.parse!(ARGV)

unless ["validate", "expand", "application", "count", "bitrise-env", "assert-pipeline-coverage"].include?(command)
  warn parser
  CliOutput.die("Unknown command #{command.inspect}")
end

changed_files = []
changed_files.concat(File.readlines(options.fetch(:changed_files_file), chomp: true)) if options.key?(:changed_files_file)
changed_files.concat(options.fetch(:changed_files, []))
changed_files = nil unless options.key?(:changed_files_file) || options.key?(:changed_files)

run_plan = E2EMatrixToBrowserStackRunPlan.load(options.fetch(:config), changed_files: changed_files)

case command
when "validate"
  errors = run_plan.validation_errors
  if errors.empty?
    puts "E2E matrix is valid"
  else
    CliOutput.die(errors.join("\n"))
  end
when "expand"
  errors = run_plan.validation_errors
  unless errors.empty?
    CliOutput.die(errors.join("\n"))
  end

  output = if options.key?(:index)
    run_plan.run_at(options.fetch(:index))
  else
    run_plan.expand
  end

  puts JSON.pretty_generate(output)
when "application"
  application_id = options.fetch(:application) { CliOutput.die("--application ID is required") }
  puts JSON.generate(run_plan.application_config(application_id))
when "count"
  errors = run_plan.validation_errors
  unless errors.empty?
    CliOutput.die(errors.join("\n"))
  end

  puts run_plan.count
when "bitrise-env"
  errors = run_plan.validation_errors
  unless errors.empty?
    CliOutput.die(errors.join("\n"))
  end

  run_plan.bitrise_env.each do |key, value|
    puts "#{key}=#{value}"
  end
when "assert-pipeline-coverage"
  pipeline_config_path = options.fetch(:pipeline_config) { CliOutput.die("--pipeline-config PATH is required") }
  pipeline_config = YAML.safe_load_file(pipeline_config_path, aliases: true) || {}
  available_workflows = (pipeline_config.dig("pipelines", "e2e", "workflows") || {}).keys
  errors = run_plan.missing_build_workflow_errors(available_workflows)
  unless errors.empty?
    CliOutput.die(errors.join("\n"), hint: E2EMatrixToBrowserStackRunPlan::MISSING_BUILD_WORKFLOW_HINT)
  end
  puts "E2E pipeline covers the run plan"
end
