#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "optparse"
require_relative "../lib/e2e_matrix"

options = {
  config: "e2e/config/matrix.yml"
}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: e2e/scripts/e2e_matrix validate|expand [options]"
  opts.on("--config PATH") { |path| options[:config] = path }
  opts.on("--index INDEX", Integer) { |index| options[:index] = index }
end

command = ARGV.shift
parser.parse!(ARGV)

unless ["validate", "expand"].include?(command)
  warn parser
  exit 1
end

matrix = E2EMatrix.load(options.fetch(:config))

case command
when "validate"
  errors = matrix.validation_errors
  if errors.empty?
    puts "E2E matrix is valid"
  else
    warn errors.join("\n")
    exit 1
  end
when "expand"
  errors = matrix.validation_errors
  unless errors.empty?
    warn errors.join("\n")
    exit 1
  end

  output = if options.key?(:index)
    matrix.run_at(options.fetch(:index))
  else
    matrix.expand
  end

  puts JSON.pretty_generate(output)
end
