#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/pull_request_changed_files"

repository = ENV.fetch("GITHUB_REPOSITORY", "Shopify/checkout-kit")
pull_request = ENV.fetch("BITRISE_PULL_REQUEST")
token = ENV["GITHUB_TOKEN"] || ENV["GIT_HTTP_PASSWORD"]
raise "GITHUB_TOKEN or GIT_HTTP_PASSWORD is required to fetch PR changed files" if token.to_s.empty?

changed_files = PullRequestChangedFiles.new(
  repository: repository,
  pull_request: pull_request,
  token: token
)

changed_files.filenames.each { |filename| puts filename }
