#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const protocolRoot = path.resolve(scriptDir, '..');

const outputPath = path.resolve(
  protocolRoot,
  'languages/typescript/src/generated/ProtocolCodecs.ts',
);
const modelsPath = path.resolve(
  protocolRoot,
  'languages/typescript/src/generated/Models.ts',
);

function collectWireToJsMappings() {
  const modelsSource = fs.readFileSync(modelsPath, 'utf8');
  const mappings = new Map();
  const propPattern = /\{\s*json: "([^"]+)", js: "([^"]+)", typ:/g;

  for (const match of modelsSource.matchAll(propPattern)) {
    const [, wireName, jsName] = match;
    if (wireName !== jsName) {
      mappings.set(wireName, jsName);
    }
  }

  if (mappings.size === 0) {
    throw new Error(
      `No wire-to-JS property mappings found in ${modelsPath}; quicktype output may have changed`,
    );
  }

  return [...mappings.entries()].sort(([left], [right]) =>
    left.localeCompare(right),
  );
}

function renderWireToJsMap(mappings) {
  return `const WIRE_TO_JS: Record<string, string> = {
${mappings
  .map(([wireName, jsName]) => `  ${propertyKey(wireName)}: '${jsName}',`)
  .join('\n')}
};`;
}

function propertyKey(value) {
  return /^[$A-Z_a-z][$\w]*$/.test(value) ? value : `'${value}'`;
}

function renderModule() {
  const wireToJsMap = renderWireToJsMap(collectWireToJsMappings());

  return `// This file is generated by protocol/scripts/generate_typescript_codecs.mjs.
// Do not edit directly.

import type {
  AddressChangeResult,
  AuthRequest,
  AuthResult,
  Checkout,
  CredentialResult,
  ErrorResponse,
  InstrumentsChangeResult,
  ReadyRequest,
  ReadyResult,
  WindowOpenRequest,
  WindowOpenResult,
} from './Models';

type JSONRecord = Record<string, unknown>;

${wireToJsMap}

const JS_TO_WIRE: Record<string, string> = Object.fromEntries(
  Object.entries(WIRE_TO_JS).map(([wire, js]) => [js, wire]),
);

const TYPED_DYNAMIC_MAP_FIELDS = new Set([
  'capabilities',
  'payment_handlers',
  'paymentHandlers',
  'services',
]);

const FREE_FORM_MAP_FIELDS = new Set([
  'attribution',
  'constraints',
  'display',
  'port',
]);

const REQUIRED_CHECKOUT_FIELDS = [
  'currency',
  'id',
  'line_items',
  'links',
  'status',
  'totals',
  'ucp',
] as const;

const REQUIRED_ERROR_FIELDS = ['messages', 'ucp'] as const;
const REQUIRED_UCP_FIELDS = ['version'] as const;

export function decodeCheckout(value: unknown): Checkout {
  const input = requireObject(value, 'checkout');
  requireFields(input, REQUIRED_CHECKOUT_FIELDS, 'checkout');
  return camelizeProtocolObject(input) as unknown as Checkout;
}

export function decodeErrorResponse(value: unknown): ErrorResponse {
  const input = requireObject(value, 'error');
  requireFields(input, REQUIRED_ERROR_FIELDS, 'error');
  return camelizeProtocolObject(input) as unknown as ErrorResponse;
}

export function decodeReadyRequest(value: unknown): ReadyRequest {
  return camelizeProtocolObject(requireObject(value, 'ready params')) as unknown as ReadyRequest;
}

export function decodeAuthRequest(value: unknown): AuthRequest {
  return camelizeProtocolObject(requireObject(value, 'auth params')) as unknown as AuthRequest;
}

export function decodeWindowOpenRequest(value: unknown): WindowOpenRequest {
  const input = requireObject(value, 'window.open params');
  if (typeof input.url !== 'string') {
    throw new TypeError('Invalid params');
  }
  return camelizeProtocolObject(input) as unknown as WindowOpenRequest;
}

export function encodeReadyResult(value: ReadyResult): unknown {
  return snakeifyProtocolObject(value);
}

export function encodeAuthResult(value: AuthResult): unknown {
  return snakeifyProtocolObject(value);
}

export function encodeInstrumentsChangeResult(
  value: InstrumentsChangeResult,
): unknown {
  return snakeifyProtocolObject(value);
}

export function encodeCredentialResult(value: CredentialResult): unknown {
  return snakeifyProtocolObject(value);
}

export function encodeAddressChangeResult(value: AddressChangeResult): unknown {
  return snakeifyProtocolObject(value);
}

export function encodeWindowOpenResult(value: WindowOpenResult): unknown {
  return snakeifyProtocolObject(value);
}

function camelizeProtocolValue(value: unknown, fieldName?: string): unknown {
  if (Array.isArray(value)) {
    return value.map(item => camelizeProtocolValue(item));
  }
  if (value === null || typeof value !== 'object') {
    return value;
  }

  if (fieldName !== undefined && FREE_FORM_MAP_FIELDS.has(fieldName)) {
    return value;
  }

  if (fieldName === 'config') {
    return isEmbeddedTransportConfig(value)
      ? camelizeProtocolObject(value as JSONRecord)
      : value;
  }

  if (fieldName !== undefined && TYPED_DYNAMIC_MAP_FIELDS.has(fieldName)) {
    return mapDynamicRecord(value, item => camelizeProtocolValue(item));
  }

  return camelizeProtocolObject(value as JSONRecord);
}

function camelizeProtocolObject(value: JSONRecord): JSONRecord {
  const output: JSONRecord = {};
  for (const [key, item] of Object.entries(value)) {
    const mappedKey = WIRE_TO_JS[key] ?? key;
    output[mappedKey] = camelizeProtocolValue(item, key);
  }
  return output;
}

function snakeifyProtocolValue(value: unknown, fieldName?: string): unknown {
  if (Array.isArray(value)) {
    return value.map(item => snakeifyProtocolValue(item));
  }
  if (value === null || typeof value !== 'object') {
    return value;
  }

  if (fieldName !== undefined && FREE_FORM_MAP_FIELDS.has(fieldName)) {
    return value;
  }

  if (fieldName === 'config') {
    return isEmbeddedTransportConfig(value)
      ? snakeifyProtocolObject(value as JSONRecord)
      : value;
  }

  if (fieldName !== undefined && TYPED_DYNAMIC_MAP_FIELDS.has(fieldName)) {
    return mapDynamicRecord(value, item => snakeifyProtocolValue(item));
  }

  return snakeifyProtocolObject(value as JSONRecord);
}

function snakeifyProtocolObject(value: JSONRecord): JSONRecord {
  const output: JSONRecord = {};
  for (const [key, item] of Object.entries(value)) {
    const mappedKey = JS_TO_WIRE[key] ?? key;
    output[mappedKey] = snakeifyProtocolValue(item, key);
  }
  return output;
}

function mapDynamicRecord(
  value: unknown,
  mapValue: (value: unknown) => unknown,
): unknown {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return value;
  }
  const output: JSONRecord = {};
  for (const [key, item] of Object.entries(value as JSONRecord)) {
    output[key] = Array.isArray(item)
      ? item.map(entry => mapValue(entry))
      : mapValue(item);
  }
  return output;
}

function requireObject(value: unknown, label: string): JSONRecord {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new TypeError(\`Invalid \${label}\`);
  }
  return value as JSONRecord;
}

function isEmbeddedTransportConfig(value: unknown): boolean {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return false;
  }
  const object = value as JSONRecord;
  return 'color_scheme' in object || 'colorScheme' in object || 'delegate' in object;
}

function requireFields(
  value: JSONRecord,
  fields: readonly string[],
  label: string,
): void {
  for (const field of fields) {
    if (!(field in value)) {
      throw new TypeError(\`Invalid \${label}\`);
    }
  }
  if ('ucp' in value) {
    const ucp = requireObject(value.ucp, \`\${label}.ucp\`);
    requireFields(ucp, REQUIRED_UCP_FIELDS, \`\${label}.ucp\`);
  }
}
`;
}

function main() {
  const generated = renderModule();
  fs.mkdirSync(path.dirname(outputPath), {recursive: true});
  fs.writeFileSync(outputPath, generated);
  console.log(`Generated ${outputPath}`);
}

main();
