#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

import {
  DELEGATIONS,
  EC_METHODS,
  delegationToIdentifier,
} from './method_catalog.mjs';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const protocolRoot = path.resolve(scriptDir, '..');

const outputPath = path.resolve(
  protocolRoot,
  'languages/typescript/src/generated/ProtocolNotifications.ts',
);
const codecsOutputPath = path.resolve(
  protocolRoot,
  'languages/typescript/src/generated/ProtocolCodecs.ts',
);

const SPEC_VERSION = '2026-04-08';

// TypeScript-specific notification decode wiring: each payload model maps to its
// generated `Convert` entrypoint and the JSON-RPC params wrapper key it arrives
// under on the wire. Mirrors the Swift/Kotlin catalogs' per-payload bindings. A
// notification whose payload has no binding fails loudly rather than silently
// dropping out of the catalog.
const NOTIFICATION_BINDINGS = new Map([
  ['Checkout', {decoder: 'decodeCheckout', wrapperKey: 'checkout'}],
  ['ErrorResponse', {decoder: 'decodeErrorResponse', wrapperKey: 'error'}],
]);

function notificationBinding(entry) {
  const binding = NOTIFICATION_BINDINGS.get(entry.payload);
  if (binding === undefined) {
    throw new Error(
      `No TypeScript notification binding for payload ${entry.payload} (${entry.method})`,
    );
  }
  return binding;
}

// A descriptor consumes raw JSON-RPC `params` from `Client.process`, so it
// unwraps the `{wrapperKey: ...}` envelope before conversion — matching the
// Swift/Kotlin notification descriptors and the `checkoutUnwrap` request path.
function notificationDecodeExpr(binding) {
  return (
    `params => ${binding.decoder}((params as {${binding.wrapperKey}: unknown}).${binding.wrapperKey})`
  );
}

// TypeScript request decode wiring. `whole` decodes the params object straight
// into the payload type (ready/auth); `checkoutUnwrap` decodes the `{checkout}`
// wrapper and extracts it. Mirrors the Swift/Kotlin catalogs' decode closures.
function requestDecodeExpr(entry) {
  switch (entry.decode) {
    case 'whole':
      return `params => decode${entry.payload}(params ?? {})`;
    case 'checkoutUnwrap':
      return `params => decodeCheckout((params as {checkout: unknown}).checkout)`;
    default:
      throw new Error(`Unknown decode strategy: ${entry.decode} (${entry.method})`);
  }
}

function requestEncodeExpr(entry) {
  return `result => encode${entry.result}(result)`;
}

function requestDelegationExpr(entry) {
  if (entry.delegation === null) {
    return 'null';
  }
  return `Delegations.${delegationToIdentifier(entry.delegation)}`;
}

function collectNotifications() {
  return EC_METHODS.filter(entry => entry.kind === 'notification').map(
    entry => {
      const binding = notificationBinding(entry);
      return {
        identifier: entry.identifier,
        method: entry.method,
        typeName: entry.payload,
        decoder: binding.decoder,
        decodeExpr: notificationDecodeExpr(binding),
      };
    },
  );
}

function collectRequests() {
  return EC_METHODS.filter(entry => entry.kind === 'request').map(entry => ({
    identifier: entry.descriptorIdentifier,
    method: entry.method,
    payload: entry.payload,
    result: entry.result,
    decodeExpr: requestDecodeExpr(entry),
    encodeExpr: requestEncodeExpr(entry),
    delegationExpr: requestDelegationExpr(entry),
  }));
}

function modelImports(notifications, requests) {
  const names = new Set();
  for (const notification of notifications) {
    names.add(notification.typeName);
  }
  for (const request of requests) {
    names.add(request.payload);
    names.add(request.result);
  }
  return Array.from(names).sort();
}

function renderModule(notifications, requests) {
  const typeNames = modelImports(notifications, requests);
  const allMethods = EC_METHODS.map(entry => entry.method);
  const codecNames = new Set();
  for (const notification of notifications) {
    codecNames.add(`decode${notification.typeName}`);
  }
  for (const request of requests) {
    codecNames.add(`decode${request.payload}`);
    codecNames.add(`encode${request.result}`);
  }

  return `// This file is generated by protocol/scripts/generate_typescript_notifications.mjs.
// Do not edit directly.

import {notificationDescriptor, requestDescriptor, type NotificationDescriptor, type RequestDescriptor} from '../descriptors';
import {${Array.from(codecNames).sort().join(', ')}} from './ProtocolCodecs';
import type {${typeNames.join(', ')}} from './Models';

export const SPEC_VERSION = '${SPEC_VERSION}';

export const Delegations = {
${DELEGATIONS.map(
  delegation => `  ${delegation.identifier}: '${delegation.value}',`,
).join('\n')}
} as const;

export type Delegation =
  | (typeof Delegations)[keyof typeof Delegations]
  | (string & {});

export const checkoutProtocolCatalog = {
${notifications
  .map(
    notification => `  ${notification.identifier}: '${notification.method}',`,
  )
  .join('\n')}
} as const;

export type CheckoutProtocolCatalogMethod =
  (typeof checkoutProtocolCatalog)[keyof typeof checkoutProtocolCatalog];

export interface CheckoutProtocolCatalogPayloads {
${notifications
  .map(
    notification => `  '${notification.method}': ${notification.typeName};`,
  )
  .join('\n')}
}

export type CheckoutProtocolCatalogPayloadDecoder<
  K extends keyof CheckoutProtocolCatalogPayloads,
> = (payload: unknown) => CheckoutProtocolCatalogPayloads[K];

export const checkoutProtocolCatalogPayloadDecoders = {
${notifications
  .map(
    notification =>
      `  [checkoutProtocolCatalog.${notification.identifier}]: decode${notification.typeName},`,
  )
  .join('\n')}
} satisfies {
  [K in keyof CheckoutProtocolCatalogPayloads]:
    CheckoutProtocolCatalogPayloadDecoder<K>;
};

export const notificationDescriptors = {
${notifications
  .map(
    notification =>
      `  ${notification.identifier}: notificationDescriptor<${notification.typeName}>(
    checkoutProtocolCatalog.${notification.identifier},
    ${notification.decodeExpr},
  ),`,
  )
  .join('\n')}
} satisfies {
  [K in keyof typeof checkoutProtocolCatalog]: NotificationDescriptor<
    CheckoutProtocolCatalogPayloads[(typeof checkoutProtocolCatalog)[K]]
  >;
};

export const checkoutProtocolRequestCatalog = {
${requests.map(request => `  ${request.identifier}: '${request.method}',`).join('\n')}
} as const;

export type CheckoutProtocolRequestMethod =
  (typeof checkoutProtocolRequestCatalog)[keyof typeof checkoutProtocolRequestCatalog];

export interface CheckoutProtocolRequestPayloads {
${requests.map(request => `  '${request.method}': ${request.payload};`).join('\n')}
}

export interface CheckoutProtocolRequestResults {
${requests.map(request => `  '${request.method}': ${request.result};`).join('\n')}
}

export const requestDescriptors = {
${requests
  .map(
    request =>
      `  ${request.identifier}: requestDescriptor<${request.payload}, ${request.result}>(
    checkoutProtocolRequestCatalog.${request.identifier},
    ${request.delegationExpr},
    ${request.decodeExpr},
    ${request.encodeExpr},
  ),`,
  )
  .join('\n')}
} satisfies {
  [K in keyof typeof checkoutProtocolRequestCatalog]: RequestDescriptor<
    CheckoutProtocolRequestPayloads[(typeof checkoutProtocolRequestCatalog)[K]],
    CheckoutProtocolRequestResults[(typeof checkoutProtocolRequestCatalog)[K]]
  >;
};

export const embeddedCheckoutMethods: ReadonlySet<string> = new Set([
${allMethods.map(method => `  '${method}',`).join('\n')}
]);
`;
}

function renderCodecsModule() {
  return `// This file is generated by protocol/scripts/generate_typescript_notifications.mjs.
// Do not edit directly.

import type {
  AddressChangeResult,
  AuthRequest,
  AuthResult,
  Checkout,
  CredentialResult,
  ErrorResponse,
  InstrumentsChangeResult,
  ReadyRequest,
  ReadyResult,
  WindowOpenRequest,
  WindowOpenResult,
} from './Models';

type JSONRecord = Record<string, unknown>;

const WIRE_TO_JS: Record<string, string> = {
  address_country: 'addressCountry',
  address_locality: 'addressLocality',
  address_region: 'addressRegion',
  available_instruments: 'availableInstruments',
  available_methods: 'availableMethods',
  billing_address: 'billingAddress',
  checkout_id: 'checkoutId',
  color_scheme: 'colorScheme',
  content_type: 'contentType',
  continue_url: 'continueUrl',
  display_text: 'displayText',
  earliest_fulfillment_time: 'earliestFulfillmentTime',
  extended_address: 'extendedAddress',
  expires_at: 'expiresAt',
  first_name: 'firstName',
  fulfillable_on: 'fulfillableOn',
  handler_id: 'handlerId',
  image_url: 'imageUrl',
  last_name: 'lastName',
  latest_fulfillment_time: 'latestFulfillmentTime',
  line_item_ids: 'lineItemIds',
  line_items: 'lineItems',
  method_type: 'methodType',
  occurred_at: 'occurredAt',
  parent_id: 'parentId',
  payment_handlers: 'paymentHandlers',
  permalink_url: 'permalinkUrl',
  phone_number: 'phoneNumber',
  postal_code: 'postalCode',
  selected_destination_id: 'selectedDestinationId',
  selected_instrument_id: 'selectedInstrumentId',
  selected_option_id: 'selectedOptionId',
  street_address: 'streetAddress',
  tracking_number: 'trackingNumber',
  tracking_url: 'trackingUrl',
};

const JS_TO_WIRE: Record<string, string> = Object.fromEntries(
  Object.entries(WIRE_TO_JS).map(([wire, js]) => [js, wire]),
);

const TYPED_DYNAMIC_MAP_FIELDS = new Set([
  'capabilities',
  'payment_handlers',
  'paymentHandlers',
  'services',
]);

const FREE_FORM_MAP_FIELDS = new Set([
  'attribution',
  'constraints',
  'display',
  'port',
]);

const REQUIRED_CHECKOUT_FIELDS = [
  'currency',
  'id',
  'line_items',
  'links',
  'status',
  'totals',
  'ucp',
] as const;

const REQUIRED_ERROR_FIELDS = ['messages', 'ucp'] as const;
const REQUIRED_UCP_FIELDS = ['version'] as const;

export function decodeCheckout(value: unknown): Checkout {
  const input = requireObject(value, 'checkout');
  requireFields(input, REQUIRED_CHECKOUT_FIELDS, 'checkout');
  return camelizeProtocolObject(input) as unknown as Checkout;
}

export function decodeErrorResponse(value: unknown): ErrorResponse {
  const input = requireObject(value, 'error');
  requireFields(input, REQUIRED_ERROR_FIELDS, 'error');
  return camelizeProtocolObject(input) as unknown as ErrorResponse;
}

export function decodeReadyRequest(value: unknown): ReadyRequest {
  return camelizeProtocolObject(requireObject(value, 'ready params')) as unknown as ReadyRequest;
}

export function decodeAuthRequest(value: unknown): AuthRequest {
  return camelizeProtocolObject(requireObject(value, 'auth params')) as unknown as AuthRequest;
}

export function decodeWindowOpenRequest(value: unknown): WindowOpenRequest {
  const input = requireObject(value, 'window.open params');
  if (typeof input.url !== 'string') {
    throw new TypeError('Invalid params');
  }
  return camelizeProtocolObject(input) as unknown as WindowOpenRequest;
}

export function encodeReadyResult(value: ReadyResult): unknown {
  return snakeifyProtocolObject(value);
}

export function encodeAuthResult(value: AuthResult): unknown {
  return snakeifyProtocolObject(value);
}

export function encodeInstrumentsChangeResult(
  value: InstrumentsChangeResult,
): unknown {
  return snakeifyProtocolObject(value);
}

export function encodeCredentialResult(value: CredentialResult): unknown {
  return snakeifyProtocolObject(value);
}

export function encodeAddressChangeResult(value: AddressChangeResult): unknown {
  return snakeifyProtocolObject(value);
}

export function encodeWindowOpenResult(value: WindowOpenResult): unknown {
  return snakeifyProtocolObject(value);
}

function camelizeProtocolValue(value: unknown, fieldName?: string): unknown {
  if (Array.isArray(value)) {
    return value.map(item => camelizeProtocolValue(item));
  }
  if (value === null || typeof value !== 'object') {
    return value;
  }

  if (fieldName !== undefined && FREE_FORM_MAP_FIELDS.has(fieldName)) {
    return value;
  }

  if (fieldName === 'config') {
    return isEmbeddedTransportConfig(value)
      ? camelizeProtocolObject(value as JSONRecord)
      : value;
  }

  if (fieldName !== undefined && TYPED_DYNAMIC_MAP_FIELDS.has(fieldName)) {
    return mapDynamicRecord(value, item => camelizeProtocolValue(item));
  }

  return camelizeProtocolObject(value as JSONRecord);
}

function camelizeProtocolObject(value: JSONRecord): JSONRecord {
  const output: JSONRecord = {};
  for (const [key, item] of Object.entries(value)) {
    const mappedKey = WIRE_TO_JS[key] ?? key;
    output[mappedKey] = camelizeProtocolValue(item, key);
  }
  return output;
}

function snakeifyProtocolValue(value: unknown, fieldName?: string): unknown {
  if (Array.isArray(value)) {
    return value.map(item => snakeifyProtocolValue(item));
  }
  if (value === null || typeof value !== 'object') {
    return value;
  }

  if (fieldName !== undefined && FREE_FORM_MAP_FIELDS.has(fieldName)) {
    return value;
  }

  if (fieldName === 'config') {
    return isEmbeddedTransportConfig(value)
      ? snakeifyProtocolObject(value as JSONRecord)
      : value;
  }

  if (fieldName !== undefined && TYPED_DYNAMIC_MAP_FIELDS.has(fieldName)) {
    return mapDynamicRecord(value, item => snakeifyProtocolValue(item));
  }

  return snakeifyProtocolObject(value as JSONRecord);
}

function snakeifyProtocolObject(value: JSONRecord): JSONRecord {
  const output: JSONRecord = {};
  for (const [key, item] of Object.entries(value)) {
    const mappedKey = JS_TO_WIRE[key] ?? key;
    output[mappedKey] = snakeifyProtocolValue(item, key);
  }
  return output;
}

function mapDynamicRecord(
  value: unknown,
  mapValue: (value: unknown) => unknown,
): unknown {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return value;
  }
  const output: JSONRecord = {};
  for (const [key, item] of Object.entries(value as JSONRecord)) {
    output[key] = Array.isArray(item)
      ? item.map(entry => mapValue(entry))
      : mapValue(item);
  }
  return output;
}

function requireObject(value: unknown, label: string): JSONRecord {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new TypeError(\`Invalid \${label}\`);
  }
  return value as JSONRecord;
}

function isEmbeddedTransportConfig(value: unknown): boolean {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return false;
  }
  const object = value as JSONRecord;
  return 'color_scheme' in object || 'colorScheme' in object || 'delegate' in object;
}

function requireFields(
  value: JSONRecord,
  fields: readonly string[],
  label: string,
): void {
  for (const field of fields) {
    if (!(field in value)) {
      throw new TypeError(\`Invalid \${label}\`);
    }
  }
  if ('ucp' in value) {
    const ucp = requireObject(value.ucp, \`\${label}.ucp\`);
    requireFields(ucp, REQUIRED_UCP_FIELDS, \`\${label}.ucp\`);
  }
}
`;
}

function main() {
  const notifications = collectNotifications();
  const requests = collectRequests();
  const generatedCodecs = renderCodecsModule();
  const generated = renderModule(notifications, requests);
  fs.mkdirSync(path.dirname(codecsOutputPath), {recursive: true});
  fs.writeFileSync(codecsOutputPath, generatedCodecs);
  fs.mkdirSync(path.dirname(outputPath), {recursive: true});
  fs.writeFileSync(outputPath, generated);
  console.log(`Generated ${codecsOutputPath}`);
  console.log(`Generated ${outputPath}`);
}

main();
