import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, resolve} from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const modelsPath = resolve(here, '../languages/typescript/src/generated/Models.ts');
const outPath = resolve(here, '../languages/typescript/src/generated/CaseMap.ts');

const src = readFileSync(modelsPath, 'utf8');

// Extract the `const typeMap: any = { ... };` object literal.
const start = src.indexOf('const typeMap: any = {');
if (start === -1) throw new Error('typeMap not found');
const braceStart = src.indexOf('{', start);
let depth = 0;
let end = -1;
for (let i = braceStart; i < src.length; i++) {
  const c = src[i];
  if (c === '{') depth++;
  else if (c === '}') {
    depth--;
    if (depth === 0) {
      end = i + 1;
      break;
    }
  }
}
const literal = src.slice(braceStart, end);

// Stub helpers matching Models.ts semantics, recording structure.
const r = (name) => ({k: 'ref', name});
const a = (t) => ({k: 'arr', t});
const m = (t) => ({k: 'map', t});
const u = (...ts) => {
  const sig = ts.find((t) => t && typeof t === 'object' && t.k) ?? ts.find((t) => t !== undefined);
  return {k: 'union', sig, optional: ts.includes(undefined)};
};
const o = (props) => ({k: 'obj', props});

const typeMap = eval(`(${literal})`);

const mechanical = (s) => s.split('_').map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('');

function resolveTyp(typ) {
  if (typ && typeof typeof typ === 'object' && typ.k === 'union') return resolveTyp(typ.sig);
  return typ;
}

function classify(typ) {
  let t = typ;
  if (t && typeof t === 'object' && t.k === 'union') t = t.sig;
  if (!t || typeof t !== 'object') return null; // scalar
  if (t.k === 'arr') {
    const el = t.t;
    if (el && typeof el === 'object' && el.k === 'ref') return ['arr', el.name];
    return null; // array of scalars
  }
  if (t.k === 'map') {
    const el = t.t;
    if (el && typeof el === 'object') {
      if (el.k === 'arr' && el.t && typeof el.t === 'object' && el.t.k === 'ref') return ['map', el.t.name];
      if (el.k === 'ref') return ['map', el.name];
    }
    return ['map'];
  }
  if (t.k === 'ref') return ['ref', t.name];
  return null;
}

const isOptional = (typ) => Boolean(typ && typeof typ === 'object' && typ.k === 'union' && typ.optional);

function requiredKind(typ) {
  let t = typ;
  if (t && typeof t === 'object' && t.k === 'union') t = t.sig;
  if (typeof t === 'string') return 'string';
  if (typeof t === 'number') return 'number';
  if (typeof t === 'boolean') return 'boolean';
  return 'any';
}

const shapes = {};
const required = {};
for (const [typeName, desc] of Object.entries(typeMap)) {
  if (!desc || desc.k !== 'obj') continue;
  const fields = {};
  const reqs = [];
  for (const prop of desc.props) {
    const {json, js, typ} = prop;
    const shape = classify(typ);
    const irregular = mechanical(json) !== js;
    if (shape) {
      fields[json] = shape;
    } else if (irregular) {
      fields[json] = ['key', js];
    }
    if (!isOptional(typ)) reqs.push([json, requiredKind(typ)]);
  }
  if (Object.keys(fields).length) shapes[typeName] = fields;
  if (reqs.length) required[typeName] = reqs;
}

const banner = `// This file is generated by protocol/scripts/generate_case_map.mjs.\n// Do not edit directly.\n\n`;
const body =
  `export type Shape =\n` +
  `  | readonly ['ref', string]\n` +
  `  | readonly ['arr', string]\n` +
  `  | readonly ['map']\n` +
  `  | readonly ['map', string]\n` +
  `  | readonly ['key', string];\n\n` +
  `export const SHAPES: Record<string, Record<string, Shape>> = ${JSON.stringify(shapes, null, 2)};\n\n` +
  `export type RequiredKind = 'string' | 'number' | 'boolean' | 'any';\n\n` +
  `export const REQUIRED: Record<string, ReadonlyArray<readonly [string, RequiredKind]>> = ${JSON.stringify(required, null, 2)};\n`;

writeFileSync(outPath, banner + body);
console.log(`Wrote ${outPath}`);
console.log(`Types with structural fields: ${Object.keys(shapes).length}`);
const totalFields = Object.values(shapes).reduce((n, f) => n + Object.keys(f).length, 0);
console.log(`Total structural field entries: ${totalFields}`);
console.log(`Types with required fields: ${Object.keys(required).length}`);
const totalReq = Object.values(required).reduce((n, f) => n + f.length, 0);
console.log(`Total required field entries: ${totalReq}`);
