#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const protocolRoot = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(protocolRoot, "..");

const openRpcPath = path.resolve(
  protocolRoot,
  "services/shopping/embedded.openrpc.json",
);
const outputPath = path.resolve(
  repoRoot,
  "protocol/languages/kotlin/embedded-checkout-protocol/src/main/java/com/shopify/ucp/embedded/checkout/EmbeddedCheckoutProtocol.kt",
);

const specVersion = "2026-04-08";

function resolvePointer(doc, pointer) {
  if (!pointer) return doc;

  return pointer
    .split("/")
    .filter(Boolean)
    .reduce((node, rawSegment) => {
      if (node == null) return undefined;
      const segment = rawSegment.replace(/~1/g, "/").replace(/~0/g, "~");
      return node[segment];
    }, doc);
}

function resolveMethod(rawMethod, openRpcDir) {
  const ref = rawMethod?.$ref;
  if (typeof ref !== "string") {
    return rawMethod;
  }

  const [relativePath, pointer = ""] = ref.split("#");
  const targetPath = path.resolve(openRpcDir, relativePath);
  const targetDoc = JSON.parse(fs.readFileSync(targetPath, "utf8"));
  return resolvePointer(targetDoc, pointer);
}

function methodNameToIdentifier(methodName) {
  // Drop the leading `ec` capability segment; the enclosing
  // EmbeddedCheckoutProtocol.Event namespace already conveys it.
  const [, ...parts] = methodName.split(/[._]/g).filter(Boolean);

  return parts
    .map((part, index) =>
      index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join("");
}

function collectEvents(openRpc, openRpcDir) {
  const events = [];

  for (const rawMethod of openRpc.methods ?? []) {
    const method = resolveMethod(rawMethod, openRpcDir);
    if (typeof method?.name !== "string") {
      throw new Error("Encountered OpenRPC method without a name");
    }

    // Scope the Android catalog to the Embedded Checkout (`ec.*`) capability,
    // matching Swift. Sibling capabilities get their own generated namespaces.
    if (!method.name.startsWith("ec.")) {
      continue;
    }

    events.push({
      identifier: methodNameToIdentifier(method.name),
      method: method.name,
    });
  }

  const seen = new Set();
  for (const event of events) {
    if (seen.has(event.identifier)) {
      throw new Error(`Duplicate catalog identifier: ${event.identifier}`);
    }
    seen.add(event.identifier);
  }

  return events;
}

function renderModule(events) {
  return `// This file is generated by protocol/scripts/generate_kotlin_catalog.mjs.
// Do not edit directly.

package com.shopify.ucp.embedded.checkout

import java.net.URI
import java.net.URLDecoder
import java.net.URLEncoder
import java.nio.charset.StandardCharsets

/**
 * Low-level Embedded Checkout Protocol constants, raw method catalog, and
 * typed spec descriptors.
 *
 * This module intentionally does not decide which protocol methods Checkout Kit
 * exposes to app developers. Host SDKs build their curated typed APIs on top of
 * these wire-level names, descriptors, and generated payload models.
 */
public object EmbeddedCheckoutProtocol {
    public const val SPEC_VERSION: String = "${specVersion}"

    public val start: NotificationDescriptor<Checkout>
        get() = embeddedCheckoutStartDescriptor

    public val complete: NotificationDescriptor<Checkout>
        get() = embeddedCheckoutCompleteDescriptor

    public val messagesChange: NotificationDescriptor<Checkout>
        get() = embeddedCheckoutMessagesChangeDescriptor

    public val lineItemsChange: NotificationDescriptor<Checkout>
        get() = embeddedCheckoutLineItemsChangeDescriptor

    public val totalsChange: NotificationDescriptor<Checkout>
        get() = embeddedCheckoutTotalsChangeDescriptor

    public val error: NotificationDescriptor<ErrorResponse>
        get() = embeddedCheckoutErrorDescriptor

    public val windowOpen: DelegationDescriptor<WindowOpenRequest, WindowOpenResult>
        get() = embeddedCheckoutWindowOpenDescriptor

    /**
     * Returns the given checkout URL with the query parameters required to
     * initiate the Embedded Checkout Protocol handshake using ec_version and
     * ec_delegate query parameters.
     */
    public fun url(
        url: String,
        delegations: List<String> = emptyList(),
    ): String = runCatching {
        val uri = URI(url)
        if (uri.isOpaque) return@runCatching url

        val queryParameters = uri.rawQuery
            ?.split("&")
            ?.filter { it.isNotEmpty() }
            ?.filterNot { it.queryParameterName() in PROTOCOL_QUERY_PARAMS }
            .orEmpty()
            .toMutableList()

        queryParameters += "$EC_VERSION_PARAM=$SPEC_VERSION"
        if (delegations.isNotEmpty()) {
            queryParameters += "$EC_DELEGATE_PARAM=\${delegations.joinToString(",").encodeQueryComponent()}"
        }

        uri.withRawQuery(queryParameters.joinToString("&"))
    }.getOrElse { url }

    public object Event {
${events
  .map(
    event => `        public const val ${event.identifier}: String = "${event.method}"`,
  )
  .join("\n")}

        public val all: Set<String> = setOf(
${events.map(event => `            ${event.identifier},`).join("\n")}
        )
    }

    private val PROTOCOL_QUERY_PARAMS: Set<String> = setOf(EC_VERSION_PARAM, EC_DELEGATE_PARAM)

    private const val EC_VERSION_PARAM: String = "ec_version"
    private const val EC_DELEGATE_PARAM: String = "ec_delegate"

    private fun URI.withRawQuery(rawQuery: String): String = buildString {
        scheme?.let { append(it).append(":") }
        rawAuthority?.let { append("//").append(it) }
        append(rawPath.orEmpty())
        if (rawQuery.isNotEmpty()) append("?").append(rawQuery)
        rawFragment?.let { append("#").append(it) }
    }

    private fun String.queryParameterName(): String =
        substringBefore("=").decodeQueryComponent()

    private fun String.decodeQueryComponent(): String =
        runCatching { URLDecoder.decode(this, StandardCharsets.UTF_8.name()) }.getOrDefault(this)

    private fun String.encodeQueryComponent(): String =
        URLEncoder.encode(this, StandardCharsets.UTF_8.name())
            .replace("+", "%20")
            .replace("%2C", ",")
}
`;
}

function main() {
  const openRpc = JSON.parse(fs.readFileSync(openRpcPath, "utf8"));
  const events = collectEvents(openRpc, path.dirname(openRpcPath));
  const generated = renderModule(events);
  fs.mkdirSync(path.dirname(outputPath), {recursive: true});
  fs.writeFileSync(outputPath, generated);
  console.log(`Generated ${outputPath}`);
}

main();
