#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

import {DELEGATIONS, EC_METHODS} from "./method_catalog.mjs";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const protocolRoot = path.resolve(scriptDir, "..");

const outputPath = path.resolve(
  protocolRoot,
  "languages/kotlin/embedded-checkout-protocol/src/main/java/com/shopify/ucp/embedded/checkout/EmbeddedCheckoutProtocol.kt",
);

const specVersion = "2026-04-08";

const notifications = EC_METHODS.filter((entry) => entry.kind === "notification");
const requests = EC_METHODS.filter((entry) => entry.kind === "request");

// Kotlin-specific notification decode wiring. Kotlin needs an explicit
// KSerializer for the wrapper params object plus the field to extract; Swift
// gets this for free from Decodable. Mirrors the Swift catalog's decodeClosure.
const NOTIFICATION_BINDINGS = new Map([
  ["Checkout", {paramsSerializer: "CheckoutParams.serializer()", extract: "it.checkout"}],
  ["ErrorResponse", {paramsSerializer: "ErrorParams.serializer()", extract: "it.error"}],
]);

// Kotlin request decode wiring. `whole` decodes params straight into the payload
// type (identity); `checkoutUnwrap` decodes the `{checkout}` wrapper and extracts
// it. Mirrors the Swift catalog's decodeClosure.
function requestDecode(entry) {
  switch (entry.decode) {
    case "whole":
      return {requestSerializer: `${entry.payload}.serializer()`, decode: "it"};
    case "checkoutUnwrap":
      return {requestSerializer: "CheckoutParams.serializer()", decode: "it.checkout"};
    default:
      throw new Error(`Unknown decode strategy: ${entry.decode}`);
  }
}

function notificationBinding(entry) {
  const binding = NOTIFICATION_BINDINGS.get(entry.payload);
  if (binding === undefined) {
    throw new Error(
      `No Kotlin notification binding for payload ${entry.payload} (${entry.method})`,
    );
  }
  return binding;
}

const seenIdentifiers = new Set();
for (const entry of EC_METHODS) {
  const member = entry.kind === "request" ? entry.descriptorIdentifier : entry.identifier;
  if (seenIdentifiers.has(member)) {
    throw new Error(`Duplicate catalog identifier: ${member}`);
  }
  seenIdentifiers.add(member);
}

const notificationDescriptors = notifications
  .map((entry) => {
    const binding = notificationBinding(entry);
    return `    public val ${entry.identifier}: NotificationDescriptor<${entry.payload}> = notificationDescriptor(
        method = Event.${entry.identifier},
        paramsSerializer = ${binding.paramsSerializer},
        decode = { ${binding.extract} },
    )`;
  })
  .join("\n\n");

const requestDescriptors = requests
  .map((entry) => {
    const decode = requestDecode(entry);
    const delegation = entry.delegation === null ? "null" : `"${entry.delegation}"`;
    return `    public val ${entry.descriptorIdentifier}: RequestDescriptor<${entry.payload}, ${entry.result}> = requestDescriptor(
        method = Event.${entry.identifier},
        delegation = ${delegation},
        requestSerializer = ${decode.requestSerializer},
        responseSerializer = ${entry.result}.serializer(),
        decode = { ${decode.decode} },
        encode = { it },
    )`;
  })
  .join("\n\n");

const eventConstants = EC_METHODS
  .map((entry) => `        public const val ${entry.identifier}: String = "${entry.method}"`)
  .join("\n");

const eventAll = EC_METHODS
  .map((entry) => `            ${entry.identifier},`)
  .join("\n");

const delegationConstants = DELEGATIONS
  .map(
    (delegation) =>
      `            public val ${delegation.identifier}: Delegation = Delegation("${delegation.value}")`,
  )
  .join("\n");

const delegationAll = DELEGATIONS
  .map((delegation) => `                ${delegation.identifier},`)
  .join("\n");

const generated = `// This file is generated by protocol/scripts/generate_kotlin_catalog.mjs.
// Do not edit directly.

package com.shopify.ucp.embedded.checkout

import kotlinx.serialization.Serializable
import java.net.URI
import java.net.URLDecoder
import java.net.URLEncoder
import java.nio.charset.StandardCharsets

/**
 * Low-level Embedded Checkout Protocol constants, raw method catalog, and
 * typed spec descriptors.
 *
 * This module intentionally does not decide which protocol methods Checkout Kit
 * exposes to app developers. Host SDKs build their curated typed APIs on top of
 * these wire-level names, descriptors, and generated payload models.
 */
public object EmbeddedCheckoutProtocol {
    public const val SPEC_VERSION: String = "${specVersion}"

    /**
     * Options controlling the query parameters appended to a checkout URL when
     * initiating the Embedded Checkout Protocol handshake.
     */
    public class Options(
        public val delegations: List<Delegation> = emptyList(),
        public val colorScheme: String? = null,
        public val auth: String? = null,
    )

    /**
     * Delegations the host can request from the business, as declared by the
     * service in \`x-delegations\`. String-backed and extensible: a host may
     * advertise a delegation this build predates, so unknown values round-trip
     * intact.
     */
    public class Delegation(
        public val rawValue: String,
    ) {
        override fun equals(other: Any?): Boolean =
            other is Delegation && rawValue == other.rawValue

        override fun hashCode(): Int = rawValue.hashCode()

        override fun toString(): String = rawValue

        public companion object {
${delegationConstants}

            public val all: List<Delegation> = listOf(
${delegationAll}
            )
        }
    }

${notificationDescriptors}

${requestDescriptors}

    /**
     * Returns the given checkout URL with the query parameters required to
     * initiate the Embedded Checkout Protocol handshake using ec_version,
     * ec_delegate, ec_auth, and ec_color_scheme query parameters.
     */
    public fun url(
        url: String,
        options: Options = Options(),
    ): String = runCatching {
        val uri = URI(url)
        if (uri.isOpaque) return@runCatching url

        val queryParameters = uri.rawQuery
            ?.split("&")
            ?.filter { it.isNotEmpty() }
            ?.filterNot { it.queryParameterName() in PROTOCOL_QUERY_PARAMS }
            .orEmpty()
            .toMutableList()

        queryParameters += "$EC_VERSION_PARAM=$SPEC_VERSION"
        if (options.delegations.isNotEmpty()) {
            queryParameters += "$EC_DELEGATE_PARAM=\${options.delegations.joinToString(",") { it.rawValue }.encodeQueryComponent()}"
        }
        options.auth?.let { auth ->
            queryParameters += "$EC_AUTH_PARAM=\${auth.encodeQueryComponent()}"
        }
        options.colorScheme?.let { colorScheme ->
            queryParameters += "$EC_COLOR_SCHEME_PARAM=\${colorScheme.encodeQueryComponent()}"
        }

        uri.withRawQuery(queryParameters.joinToString("&"))
    }.getOrElse { url }

    public object Event {
${eventConstants}

        public val all: Set<String> = setOf(
${eventAll}
        )
    }

    private val PROTOCOL_QUERY_PARAMS: Set<String> = setOf(
        EC_VERSION_PARAM,
        EC_DELEGATE_PARAM,
        EC_AUTH_PARAM,
        EC_COLOR_SCHEME_PARAM,
    )

    private const val EC_VERSION_PARAM: String = "ec_version"
    private const val EC_DELEGATE_PARAM: String = "ec_delegate"
    private const val EC_AUTH_PARAM: String = "ec_auth"
    private const val EC_COLOR_SCHEME_PARAM: String = "ec_color_scheme"

    private fun URI.withRawQuery(rawQuery: String): String = buildString {
        scheme?.let { append(it).append(":") }
        rawAuthority?.let { append("//").append(it) }
        append(rawPath.orEmpty())
        if (rawQuery.isNotEmpty()) append("?").append(rawQuery)
        rawFragment?.let { append("#").append(it) }
    }

    private fun String.queryParameterName(): String =
        substringBefore("=").decodeQueryComponent()

    private fun String.decodeQueryComponent(): String =
        runCatching { URLDecoder.decode(this, StandardCharsets.UTF_8.name()) }.getOrDefault(this)

    private fun String.encodeQueryComponent(): String =
        URLEncoder.encode(this, StandardCharsets.UTF_8.name())
            .replace("+", "%20")
            .replace("%2C", ",")
}

@Serializable
private data class CheckoutParams(
    val checkout: Checkout,
)

@Serializable
private data class ErrorParams(
    val error: ErrorResponse,
)
`;

fs.mkdirSync(path.dirname(outputPath), {recursive: true});
fs.writeFileSync(outputPath, generated);
console.log(`Generated ${outputPath}`);
