#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

import {EC_METHODS} from './method_catalog.mjs';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const protocolRoot = path.resolve(scriptDir, '..');

const outputPath = path.resolve(
  protocolRoot,
  'languages/typescript/src/generated/ProtocolNotifications.ts',
);

// TypeScript-specific notification decode wiring: each payload model maps to its
// generated `Convert` entrypoint. Mirrors the Swift/Kotlin catalogs' per-payload
// bindings. A notification whose payload has no binding fails loudly rather than
// silently dropping out of the catalog.
const NOTIFICATION_BINDINGS = new Map([
  ['Checkout', 'Convert.toCheckout'],
  ['ErrorResponse', 'Convert.toErrorResponse'],
]);

function notificationConverter(entry) {
  const converter = NOTIFICATION_BINDINGS.get(entry.payload);
  if (converter === undefined) {
    throw new Error(
      `No TypeScript notification binding for payload ${entry.payload} (${entry.method})`,
    );
  }
  return converter;
}

function collectNotifications() {
  return EC_METHODS.filter(entry => entry.kind === 'notification').map(
    entry => ({
      identifier: entry.identifier,
      method: entry.method,
      typeName: entry.payload,
      converter: notificationConverter(entry),
    }),
  );
}

function renderModule(notifications) {
  const typeNames = Array.from(
    new Set(notifications.map(notification => notification.typeName)),
  ).sort();

  return `// This file is generated by protocol/scripts/generate_typescript_notifications.mjs.
// Do not edit directly.

import {Convert, type ${typeNames.join(', type ')}} from './Models';

export const checkoutProtocolCatalog = {
${notifications
  .map(
    notification => `  ${notification.identifier}: '${notification.method}',`,
  )
  .join('\n')}
} as const;

export type CheckoutProtocolCatalogMethod =
  (typeof checkoutProtocolCatalog)[keyof typeof checkoutProtocolCatalog];

export interface CheckoutProtocolCatalogPayloads {
${notifications
  .map(
    notification => `  '${notification.method}': ${notification.typeName};`,
  )
  .join('\n')}
}

export type CheckoutProtocolCatalogPayloadDecoder<
  K extends keyof CheckoutProtocolCatalogPayloads,
> = (payload: unknown) => CheckoutProtocolCatalogPayloads[K];

export const checkoutProtocolCatalogPayloadDecoders = {
${notifications
  .map(
    notification =>
      `  [checkoutProtocolCatalog.${notification.identifier}]: decodeWith(${notification.converter}),`,
  )
  .join('\n')}
} satisfies {
  [K in keyof CheckoutProtocolCatalogPayloads]:
    CheckoutProtocolCatalogPayloadDecoder<K>;
};

function decodeWith<T>(converter: (json: string) => T): (payload: unknown) => T {
  return payload => converter(JSON.stringify(payload));
}
`;
}

function main() {
  const notifications = collectNotifications();
  const generated = renderModule(notifications);
  fs.mkdirSync(path.dirname(outputPath), {recursive: true});
  fs.writeFileSync(outputPath, generated);
  console.log(`Generated ${outputPath}`);
}

main();
