import fs from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROTOCOL_DIR = path.resolve(__dirname, "..");
const MODELS = path.join(
  PROTOCOL_DIR,
  "languages/typescript/src/generated/Models.ts",
);
const OUTPUT = path.join(
  PROTOCOL_DIR,
  "languages/typescript/src/generated/ProtocolRenameMap.ts",
);

function l(typ) {
  return {literal: typ};
}
function a(typ) {
  return {arrayItems: typ};
}
function u(...typs) {
  return {unionMembers: typs};
}
function o(props, additional) {
  return {props, additional};
}
function m(additional) {
  return {props: [], additional};
}
function r(name) {
  return {ref: name};
}

async function loadTypeMap() {
  const source = await fs.readFile(MODELS, "utf8");
  const marker = "export const typeMap: any = {";
  const start = source.indexOf(marker);
  if (start === -1) {
    throw new Error("typeMap literal not found in Models.ts");
  }
  const literal = source.slice(start + marker.length - 1).replace(/;\s*$/, "");
  // eslint-disable-next-line no-new-func
  const factory = new Function(
    "l",
    "a",
    "u",
    "o",
    "m",
    "r",
    "Date",
    `return ${literal};`,
  );
  return factory(l, a, u, o, m, r, Date);
}

function isObjectType(typ) {
  return typ && typeof typ === "object" && Array.isArray(typ.props);
}
function isMapType(typ) {
  return isObjectType(typ) && typ.props.length === 0;
}

function computeContainsRename(typeMap) {
  const contains = new Set();
  let changed = true;
  while (changed) {
    changed = false;
    for (const [name, typ] of Object.entries(typeMap)) {
      if (contains.has(name) || !isObjectType(typ)) {
        continue;
      }
      if (typ.props.some(prop => propHasRename(prop, typeMap, contains))) {
        contains.add(name);
        changed = true;
      }
    }
  }
  return contains;
}

function propHasRename(prop, typeMap, contains) {
  if (prop.json !== prop.js) {
    return true;
  }
  return typeHasRename(prop.typ, typeMap, contains);
}

function typeHasRename(typ, typeMap, contains) {
  if (!typ || typeof typ !== "object") {
    return false;
  }
  if (typeof typ.ref === "string") {
    return contains.has(typ.ref);
  }
  if (typ.arrayItems !== undefined) {
    return typeHasRename(typ.arrayItems, typeMap, contains);
  }
  if (Array.isArray(typ.unionMembers)) {
    return typ.unionMembers.some(member =>
      typeHasRename(member, typeMap, contains),
    );
  }
  if (isMapType(typ)) {
    return typeHasRename(typ.additional, typeMap, contains);
  }
  return false;
}

function pruneChild(typ, typeMap, contains) {
  if (!typ || typeof typ !== "object") {
    return undefined;
  }
  if (typeof typ.ref === "string") {
    return contains.has(typ.ref) ? ["r", typ.ref] : undefined;
  }
  if (typ.arrayItems !== undefined) {
    const child = pruneChild(typ.arrayItems, typeMap, contains);
    return child ? ["a", child] : undefined;
  }
  if (isMapType(typ)) {
    const child = pruneChild(typ.additional, typeMap, contains);
    return child ? ["m", child] : undefined;
  }
  if (Array.isArray(typ.unionMembers)) {
    const children = typ.unionMembers
      .map(member => pruneChild(member, typeMap, contains))
      .filter(Boolean);
    if (children.length === 0) {
      return undefined;
    }
    return children.length === 1 ? children[0] : ["u", ...children];
  }
  return undefined;
}

function buildRenameMap(typeMap, contains) {
  const renameMap = {};
  for (const name of contains) {
    const typ = typeMap[name];
    const entries = [];
    for (const prop of typ.props) {
      const child = pruneChild(prop.typ, typeMap, contains);
      if (prop.json === prop.js && !child) {
        continue;
      }
      entries.push(child ? [prop.json, prop.js, child] : [prop.json, prop.js]);
    }
    if (entries.length > 0) {
      renameMap[name] = entries;
    }
  }
  return renameMap;
}

async function main() {
  const typeMap = await loadTypeMap();
  const contains = computeContainsRename(typeMap);
  const renameMap = buildRenameMap(typeMap, contains);
  const sorted = Object.fromEntries(
    Object.keys(renameMap)
      .sort()
      .map(key => [key, renameMap[key]]),
  );
  const body = `// This file is generated by protocol/scripts/generate_typescript_rename_map.mjs.
// Do not edit directly.
//
// A pruned rename spine derived from the quicktype typeMap. It contains only
// props that require snake_case <-> camelCase renaming, plus the structural
// path needed to reach them. Extension keys (UCP additionalProperties) are
// preserved by the walker's pass-through and are intentionally absent here.

export type RenameChild =
  | ['r', string]
  | ['a', RenameChild]
  | ['m', RenameChild]
  | ['u', ...RenameChild[]];

export type RenameEntry = [string, string] | [string, string, RenameChild];

export const renameMap: Record<string, RenameEntry[]> = ${JSON.stringify(
    sorted,
  )};
`;
  await fs.writeFile(OUTPUT, body);
  const count = Object.values(renameMap).reduce(
    (sum, entries) => sum + entries.length,
    0,
  );
  console.log(
    `Generated ${OUTPUT} (${Object.keys(renameMap).length} models, ${count} entries)`,
  );
}

await main();
