#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const protocolRoot = path.resolve(scriptDir, '..');

const openRpcPath = path.resolve(
  protocolRoot,
  'services/shopping/embedded.openrpc.json',
);
const outputPath = path.resolve(
  protocolRoot,
  'languages/typescript/src/generated/ProtocolNotifications.ts',
);

const refMappings = new Map([
  [
    'checkout.json',
    {
      typeName: 'Checkout',
      converter: 'Convert.toCheckout',
    },
  ],
  [
    'types/error_response.json',
    {
      typeName: 'ErrorResponse',
      converter: 'Convert.toErrorResponse',
    },
  ],
  [
    'common/types/error_response.json',
    {
      typeName: 'ErrorResponse',
      converter: 'Convert.toErrorResponse',
    },
  ],
]);

function normalizeRef(ref) {
  return ref
    .replace(/^\.\.\/\.\.\/schemas\/shopping\//, '')
    .replace(/^\.\.\/\.\.\/schemas\//, '');
}

function methodNameToIdentifier(methodName) {
  const suffix = methodName.replace(/^ec\./, '');
  const parts = suffix.split(/[._]/g).filter(Boolean);

  return parts
    .map((part, index) =>
      index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join('');
}

function isNotification(method) {
  return (
    typeof method.name === 'string' &&
    method.name.startsWith('ec.') &&
    !Object.prototype.hasOwnProperty.call(method, 'result')
  );
}

const openRpc = JSON.parse(fs.readFileSync(openRpcPath, 'utf8'));
const notifications = [];

for (const method of openRpc.methods ?? []) {
  if (!isNotification(method)) continue;

  const params = method.params ?? [];
  if (params.length !== 1) {
    throw new Error(
      `Cannot generate notification ${method.name}: expected exactly one param, got ${params.length}`,
    );
  }

  const [param] = params;
  const ref = param?.schema?.$ref;
  if (typeof ref !== 'string') {
    throw new Error(
      `Cannot generate notification ${method.name}: expected param schema.$ref`,
    );
  }

  const normalizedRef = normalizeRef(ref);
  const mapping = refMappings.get(normalizedRef);
  if (!mapping) {
    throw new Error(
      `Cannot generate notification ${method.name}: unsupported schema ref ${ref}`,
    );
  }

  notifications.push({
    identifier: methodNameToIdentifier(method.name),
    method: method.name,
    typeName: mapping.typeName,
    converter: mapping.converter,
  });
}

const typeNames = Array.from(
  new Set(notifications.map(notification => notification.typeName)),
).sort();

const generated = `// This file is generated by protocol/scripts/generate_typescript_notifications.mjs.
// Do not edit directly.

import {Convert, type ${typeNames.join(', type ')}} from './Models';

export const generatedCheckoutProtocol = {
${notifications
  .map(
    notification => `  ${notification.identifier}: '${notification.method}',`,
  )
  .join('\n')}
} as const;

export type GeneratedCheckoutProtocolMethod =
  (typeof generatedCheckoutProtocol)[keyof typeof generatedCheckoutProtocol];

export interface GeneratedCheckoutProtocolPayloads {
${notifications
  .map(
    notification => `  '${notification.method}': ${notification.typeName};`,
  )
  .join('\n')}
}

export type GeneratedCheckoutProtocolPayloadDecoder<
  K extends keyof GeneratedCheckoutProtocolPayloads,
> = (payload: unknown) => GeneratedCheckoutProtocolPayloads[K];

export const generatedCheckoutProtocolPayloadDecoders = {
${notifications
  .map(
    notification =>
      `  [generatedCheckoutProtocol.${notification.identifier}]: decodeWith(${notification.converter}),`,
  )
  .join('\n')}
} satisfies {
  [K in keyof GeneratedCheckoutProtocolPayloads]:
    GeneratedCheckoutProtocolPayloadDecoder<K>;
};

function decodeWith<T>(converter: (json: string) => T): (payload: unknown) => T {
  return payload => converter(JSON.stringify(payload));
}
`;

fs.mkdirSync(path.dirname(outputPath), {recursive: true});
fs.writeFileSync(outputPath, generated);
console.log(`Generated ${outputPath}`);
