#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

import {EC_METHODS} from './method_catalog.mjs';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const protocolRoot = path.resolve(scriptDir, '..');

const outputPath = path.resolve(
  protocolRoot,
  'languages/typescript/src/generated/ProtocolCodecs.ts',
);

function codecModels() {
  const decodeModels = new Set();
  const encodeModels = new Set();

  for (const method of EC_METHODS) {
    if (method.kind === 'notification') {
      decodeModels.add(method.payload);
    } else {
      decodeModels.add(method.payload);
      encodeModels.add(method.result);
    }
  }

  decodeModels.delete('JSONAny');
  encodeModels.delete('JSONAny');

  return {
    decodeModels: [...decodeModels].sort(),
    encodeModels: [...encodeModels].sort(),
    allModels: [...new Set([...decodeModels, ...encodeModels])].sort(),
  };
}

function renderDecodeFunction(modelName) {
  return `export function decode${modelName}(value: unknown): ${modelName} {
  return decodeProtocolObject(value, '${modelName}') as unknown as ${modelName};
}`;
}

function renderEncodeFunction(modelName) {
  return `export function encode${modelName}(value: ${modelName}): unknown {
  return encodeProtocolObject(value);
}`;
}

function renderModule() {
  const {decodeModels, encodeModels, allModels} = codecModels();
  const typeAliases = allModels
    .map(modelName => `type ${modelName} = import('./Models').${modelName};`)
    .join('\n');

  return `// This file is generated by protocol/scripts/generate_typescript_codecs.mjs.
// Do not edit directly.

import {
  decodeProtocolObject,
  encodeProtocolObject,
} from '../protocol_codec_runtime';

${typeAliases}

${decodeModels.map(renderDecodeFunction).join('\n\n')}

${encodeModels.map(renderEncodeFunction).join('\n\n')}
`;
}

function main() {
  const generated = renderModule();
  fs.mkdirSync(path.dirname(outputPath), {recursive: true});
  fs.writeFileSync(outputPath, generated);
  console.log(`Generated ${outputPath}`);
}

main();
