#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const protocolRoot = path.resolve(scriptDir, '..');

const openRpcPath = path.resolve(
  protocolRoot,
  'services/shopping/embedded.openrpc.json',
);
const outputPath = path.resolve(
  protocolRoot,
  'languages/swift/Sources/ShopifyCheckoutProtocol/Generated/EmbeddedCheckoutProtocol+Event.swift',
);

const fallbackPayload = 'JSONAny';

const refPayloadMappings = new Map([
  ['checkout.json', 'Checkout'],
  ['cart.json', fallbackPayload],
  ['types/error_response.json', 'ErrorResponse'],
  ['error_response.json', 'ErrorResponse'],
]);

function normalizeRef(ref) {
  return ref
    .replace(/^\.\.\/\.\.\/schemas\/shopping\//, '')
    .replace(/^\.\.\/\.\.\/schemas\/common\//, '')
    .replace(/#.*$/, '');
}

function methodNameToIdentifier(methodName) {
  // Drop the leading `ec` capability segment; the enclosing
  // EmbeddedCheckoutProtocol.Event namespace already conveys it.
  const [, ...parts] = methodName.split(/[._]/g).filter(Boolean);

  return parts
    .map((part, index) =>
      index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join('');
}

function delegationToIdentifier(delegation) {
  return delegation
    .split(/[._]/g)
    .filter(Boolean)
    .map((part, index) =>
      index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join('');
}

function resolveMethod(method, openRpcDir) {
  if (typeof method.$ref !== 'string') {
    return method;
  }

  const [filePart, pointer] = method.$ref.split('#');
  const filePath = path.resolve(openRpcDir, filePart);
  const document = JSON.parse(fs.readFileSync(filePath, 'utf8'));

  const segments = (pointer ?? '').split('/').filter(Boolean);
  let resolved = document;
  for (const segment of segments) {
    resolved = resolved?.[segment.replace(/~1/g, '/').replace(/~0/g, '~')];
  }

  if (!resolved || typeof resolved.name !== 'string') {
    throw new Error(`Cannot resolve OpenRPC method $ref: ${method.$ref}`);
  }

  return resolved;
}

function payloadType(method) {
  const params = method.params ?? [];
  if (params.length === 0) {
    return fallbackPayload;
  }

  const ref = params[0]?.schema?.$ref;
  if (typeof ref !== 'string') {
    return fallbackPayload;
  }

  const normalized = normalizeRef(ref);
  return refPayloadMappings.get(normalized) ?? fallbackPayload;
}

const openRpcDir = path.dirname(openRpcPath);
const openRpc = JSON.parse(fs.readFileSync(openRpcPath, 'utf8'));
const entries = [];

for (const rawMethod of openRpc.methods ?? []) {
  const method = resolveMethod(rawMethod, openRpcDir);
  if (typeof method.name !== 'string') {
    throw new Error('Encountered OpenRPC method without a name');
  }

  // Scope the Swift catalog to the Embedded Checkout (`ec.*`) capability.
  // Sibling capabilities (e.g. `ep.cart.*`) are excluded until they have a
  // typed payload and a consumer.
  if (!method.name.startsWith('ec.')) {
    continue;
  }

  entries.push({
    identifier: methodNameToIdentifier(method.name),
    method: method.name,
    payload: payloadType(method),
    isRequest: method.result != null,
  });
}

const seen = new Set();
for (const entry of entries) {
  if (seen.has(entry.identifier)) {
    throw new Error(`Duplicate catalog identifier: ${entry.identifier}`);
  }
  seen.add(entry.identifier);
}

const delegations = (openRpc['x-delegations'] ?? []).map(delegation => ({
  identifier: delegationToIdentifier(delegation),
  value: delegation,
}));

const seenDelegations = new Set();
for (const delegation of delegations) {
  if (seenDelegations.has(delegation.identifier)) {
    throw new Error(`Duplicate delegation identifier: ${delegation.identifier}`);
  }
  seenDelegations.add(delegation.identifier);
}

const payloadTypes = Array.from(
  new Set(entries.filter(entry => !entry.isRequest).map(entry => entry.payload)),
).sort();

const conformances = payloadTypes
  .map(type => `extension ${type}: EventPayload {}`)
  .join('\n');

const generated = `// This file is generated by protocol/scripts/generate_swift_catalog.mjs.
// Do not edit directly.

import Foundation

${conformances}

extension EmbeddedCheckoutProtocol {
    public enum Event {
${entries
  .map(entry =>
    entry.isRequest
      ? `        public static let ${entry.identifier} = MethodDescriptor(method: "${entry.method}")`
      : `        public static let ${entry.identifier} = NotificationDescriptor<${entry.payload}>(method: "${entry.method}")`,
  )
  .join('\n')}

        public static let all: [String] = [
${entries.map(entry => `            ${entry.identifier}.method,`).join('\n')}
        ]
    }
}

extension EmbeddedCheckoutProtocol {
    /// Delegations the host can request from the business, as declared by the
    /// service in \`x-delegations\`. String-backed and open: a host may advertise
    /// a delegation this build predates, so unknown values round-trip intact.
    public struct Delegation: RawRepresentable, Hashable, Sendable, ExpressibleByStringLiteral {
        public let rawValue: String

        public init(rawValue: String) {
            self.rawValue = rawValue
        }

        public init(stringLiteral value: String) {
            self.rawValue = value
        }

${delegations
  .map(
    delegation =>
      `        public static let ${delegation.identifier} = Delegation(rawValue: "${delegation.value}")`,
  )
  .join('\n')}

        public static let all: [Delegation] = [
${delegations.map(delegation => `            .${delegation.identifier},`).join('\n')}
        ]
    }
}
`;

fs.mkdirSync(path.dirname(outputPath), {recursive: true});
fs.writeFileSync(outputPath, generated);
console.log(`Generated ${outputPath}`);
