// This file is generated by protocol/scripts/generate_kotlin_catalog.mjs.
// Do not edit directly.

package com.shopify.ucp.embedded.checkout

/**
 * Low-level Embedded Checkout Protocol constants, raw method catalog, and
 * typed spec descriptors.
 *
 * This module intentionally does not decide which protocol methods Checkout Kit
 * exposes to app developers. Host SDKs build their curated typed APIs on top of
 * these wire-level names, descriptors, and generated payload models.
 */
public object EmbeddedCheckoutProtocol {
    public const val SPEC_VERSION: String = "2026-04-08"

    public val start: NotificationDescriptor<Checkout>
        get() = embeddedCheckoutStartDescriptor

    public val complete: NotificationDescriptor<Checkout>
        get() = embeddedCheckoutCompleteDescriptor

    public val messagesChange: NotificationDescriptor<Checkout>
        get() = embeddedCheckoutMessagesChangeDescriptor

    public val lineItemsChange: NotificationDescriptor<Checkout>
        get() = embeddedCheckoutLineItemsChangeDescriptor

    public val totalsChange: NotificationDescriptor<Checkout>
        get() = embeddedCheckoutTotalsChangeDescriptor

    public val error: NotificationDescriptor<ErrorResponse>
        get() = embeddedCheckoutErrorDescriptor

    public val windowOpen: DelegationDescriptor<WindowOpenRequest, WindowOpenResult>
        get() = embeddedCheckoutWindowOpenDescriptor

    public object Event {
        public const val ready: String = "ec.ready"
        public const val auth: String = "ec.auth"
        public const val error: String = "ec.error"
        public const val start: String = "ec.start"
        public const val complete: String = "ec.complete"
        public const val messagesChange: String = "ec.messages.change"
        public const val lineItemsChange: String = "ec.line_items.change"
        public const val buyerChange: String = "ec.buyer.change"
        public const val totalsChange: String = "ec.totals.change"
        public const val paymentChange: String = "ec.payment.change"
        public const val paymentInstrumentsChangeRequest: String = "ec.payment.instruments_change_request"
        public const val paymentCredentialRequest: String = "ec.payment.credential_request"
        public const val windowOpenRequest: String = "ec.window.open_request"
        public const val fulfillmentChange: String = "ec.fulfillment.change"
        public const val fulfillmentAddressChangeRequest: String = "ec.fulfillment.address_change_request"

        public val all: Set<String> = setOf(
            ready,
            auth,
            error,
            start,
            complete,
            messagesChange,
            lineItemsChange,
            buyerChange,
            totalsChange,
            paymentChange,
            paymentInstrumentsChangeRequest,
            paymentCredentialRequest,
            windowOpenRequest,
            fulfillmentChange,
            fulfillmentAddressChangeRequest,
        )
    }
}
