// This file is generated by protocol/scripts/generate_kotlin_catalog.mjs.
// Do not edit directly.

package com.shopify.ucp.embedded.checkout

import kotlinx.serialization.Serializable
import java.net.URI
import java.net.URLDecoder
import java.net.URLEncoder
import java.nio.charset.StandardCharsets

/**
 * Low-level Embedded Checkout Protocol constants, raw method catalog, and
 * typed spec descriptors.
 *
 * This module intentionally does not decide which protocol methods Checkout Kit
 * exposes to app developers. Host SDKs build their curated typed APIs on top of
 * these wire-level names, descriptors, and generated payload models.
 */
public object EmbeddedCheckoutProtocol {
    public const val SPEC_VERSION: String = "2026-04-08"

    /**
     * Options controlling the query parameters appended to a checkout URL when
     * initiating the Embedded Checkout Protocol handshake.
     */
    public class Options(
        public val delegations: List<Delegation> = emptyList(),
        public val colorScheme: String? = null,
        public val auth: String? = null,
    )

    /**
     * Delegations the host can request from the business, as declared by the
     * service in `x-delegations`. String-backed and extensible: a host may
     * advertise a delegation this build predates, so unknown values round-trip
     * intact.
     */
    public class Delegation(
        public val rawValue: String,
    ) {
        override fun equals(other: Any?): Boolean =
            other is Delegation && rawValue == other.rawValue

        override fun hashCode(): Int = rawValue.hashCode()

        override fun toString(): String = rawValue

        public companion object {
            public val paymentInstrumentsChange: Delegation = Delegation("payment.instruments_change")
            public val paymentCredential: Delegation = Delegation("payment.credential")
            public val fulfillmentAddressChange: Delegation = Delegation("fulfillment.address_change")
            public val windowOpen: Delegation = Delegation("window.open")

            public val all: List<Delegation> = listOf(
                paymentInstrumentsChange,
                paymentCredential,
                fulfillmentAddressChange,
                windowOpen,
            )
        }
    }

    public val error: NotificationDescriptor<ErrorParams> = notificationDescriptor(
        method = Event.error,
        paramsSerializer = ErrorParams.serializer(),
        decode = { it },
    )

    public val start: NotificationDescriptor<CheckoutParams> = notificationDescriptor(
        method = Event.start,
        paramsSerializer = CheckoutParams.serializer(),
        decode = { it },
    )

    public val complete: NotificationDescriptor<CheckoutParams> = notificationDescriptor(
        method = Event.complete,
        paramsSerializer = CheckoutParams.serializer(),
        decode = { it },
    )

    public val messagesChange: NotificationDescriptor<CheckoutParams> = notificationDescriptor(
        method = Event.messagesChange,
        paramsSerializer = CheckoutParams.serializer(),
        decode = { it },
    )

    public val lineItemsChange: NotificationDescriptor<CheckoutParams> = notificationDescriptor(
        method = Event.lineItemsChange,
        paramsSerializer = CheckoutParams.serializer(),
        decode = { it },
    )

    public val buyerChange: NotificationDescriptor<CheckoutParams> = notificationDescriptor(
        method = Event.buyerChange,
        paramsSerializer = CheckoutParams.serializer(),
        decode = { it },
    )

    public val totalsChange: NotificationDescriptor<CheckoutParams> = notificationDescriptor(
        method = Event.totalsChange,
        paramsSerializer = CheckoutParams.serializer(),
        decode = { it },
    )

    public val paymentChange: NotificationDescriptor<CheckoutParams> = notificationDescriptor(
        method = Event.paymentChange,
        paramsSerializer = CheckoutParams.serializer(),
        decode = { it },
    )

    public val fulfillmentChange: NotificationDescriptor<CheckoutParams> = notificationDescriptor(
        method = Event.fulfillmentChange,
        paramsSerializer = CheckoutParams.serializer(),
        decode = { it },
    )

    public val ready: RequestDescriptor<ReadyRequest, ReadyResult> = requestDescriptor(
        method = Event.ready,
        delegation = null,
        requestSerializer = ReadyRequest.serializer(),
        responseSerializer = ReadyResult.serializer(),
        decode = { it },
        encode = { it },
    )

    public val auth: RequestDescriptor<AuthRequest, AuthResult> = requestDescriptor(
        method = Event.auth,
        delegation = null,
        requestSerializer = AuthRequest.serializer(),
        responseSerializer = AuthResult.serializer(),
        decode = { it },
        encode = { it },
    )

    public val paymentInstrumentsChange: RequestDescriptor<CheckoutParams, InstrumentsChangeResult> = requestDescriptor(
        method = Event.paymentInstrumentsChangeRequest,
        delegation = "payment.instruments_change",
        requestSerializer = CheckoutParams.serializer(),
        responseSerializer = InstrumentsChangeResult.serializer(),
        decode = { it },
        encode = { it },
    )

    public val paymentCredential: RequestDescriptor<CheckoutParams, CredentialResult> = requestDescriptor(
        method = Event.paymentCredentialRequest,
        delegation = "payment.credential",
        requestSerializer = CheckoutParams.serializer(),
        responseSerializer = CredentialResult.serializer(),
        decode = { it },
        encode = { it },
    )

    public val windowOpen: RequestDescriptor<WindowOpenRequest, WindowOpenResult> = requestDescriptor(
        method = Event.windowOpenRequest,
        delegation = "window.open",
        requestSerializer = WindowOpenRequest.serializer(),
        responseSerializer = WindowOpenResult.serializer(),
        decode = { it },
        encode = { it },
    )

    public val fulfillmentAddressChange: RequestDescriptor<CheckoutParams, AddressChangeResult> = requestDescriptor(
        method = Event.fulfillmentAddressChangeRequest,
        delegation = "fulfillment.address_change",
        requestSerializer = CheckoutParams.serializer(),
        responseSerializer = AddressChangeResult.serializer(),
        decode = { it },
        encode = { it },
    )

    /**
     * Returns the given checkout URL with the query parameters required to
     * initiate the Embedded Checkout Protocol handshake using ec_version,
     * ec_delegate, ec_auth, and ec_color_scheme query parameters.
     */
    public fun url(
        url: String,
        options: Options = Options(),
    ): String = runCatching {
        val uri = URI(url)
        if (uri.isOpaque) return@runCatching url

        val queryParameters = uri.rawQuery
            ?.split("&")
            ?.filter { it.isNotEmpty() }
            ?.filterNot { it.queryParameterName() in PROTOCOL_QUERY_PARAMS }
            .orEmpty()
            .toMutableList()

        queryParameters += "$EC_VERSION_PARAM=$SPEC_VERSION"
        if (options.delegations.isNotEmpty()) {
            queryParameters += "$EC_DELEGATE_PARAM=${options.delegations.joinToString(",") { it.rawValue }.encodeQueryComponent()}"
        }
        options.auth?.let { auth ->
            queryParameters += "$EC_AUTH_PARAM=${auth.encodeQueryComponent()}"
        }
        options.colorScheme?.let { colorScheme ->
            queryParameters += "$EC_COLOR_SCHEME_PARAM=${colorScheme.encodeQueryComponent()}"
        }

        uri.withRawQuery(queryParameters.joinToString("&"))
    }.getOrElse { url }

    public object Event {
        public const val ready: String = "ec.ready"
        public const val auth: String = "ec.auth"
        public const val error: String = "ec.error"
        public const val start: String = "ec.start"
        public const val complete: String = "ec.complete"
        public const val messagesChange: String = "ec.messages.change"
        public const val lineItemsChange: String = "ec.line_items.change"
        public const val buyerChange: String = "ec.buyer.change"
        public const val totalsChange: String = "ec.totals.change"
        public const val paymentChange: String = "ec.payment.change"
        public const val paymentInstrumentsChangeRequest: String = "ec.payment.instruments_change_request"
        public const val paymentCredentialRequest: String = "ec.payment.credential_request"
        public const val windowOpenRequest: String = "ec.window.open_request"
        public const val fulfillmentChange: String = "ec.fulfillment.change"
        public const val fulfillmentAddressChangeRequest: String = "ec.fulfillment.address_change_request"

        public val all: Set<String> = setOf(
            ready,
            auth,
            error,
            start,
            complete,
            messagesChange,
            lineItemsChange,
            buyerChange,
            totalsChange,
            paymentChange,
            paymentInstrumentsChangeRequest,
            paymentCredentialRequest,
            windowOpenRequest,
            fulfillmentChange,
            fulfillmentAddressChangeRequest,
        )
    }

    private val PROTOCOL_QUERY_PARAMS: Set<String> = setOf(
        EC_VERSION_PARAM,
        EC_DELEGATE_PARAM,
        EC_AUTH_PARAM,
        EC_COLOR_SCHEME_PARAM,
    )

    private const val EC_VERSION_PARAM: String = "ec_version"
    private const val EC_DELEGATE_PARAM: String = "ec_delegate"
    private const val EC_AUTH_PARAM: String = "ec_auth"
    private const val EC_COLOR_SCHEME_PARAM: String = "ec_color_scheme"

    private fun URI.withRawQuery(rawQuery: String): String = buildString {
        scheme?.let { append(it).append(":") }
        rawAuthority?.let { append("//").append(it) }
        append(rawPath.orEmpty())
        if (rawQuery.isNotEmpty()) append("?").append(rawQuery)
        rawFragment?.let { append("#").append(it) }
    }

    private fun String.queryParameterName(): String =
        substringBefore("=").decodeQueryComponent()

    private fun String.decodeQueryComponent(): String =
        runCatching { URLDecoder.decode(this, StandardCharsets.UTF_8.name()) }.getOrDefault(this)

    private fun String.encodeQueryComponent(): String =
        URLEncoder.encode(this, StandardCharsets.UTF_8.name())
            .replace("+", "%20")
            .replace("%2C", ",")
}

@Serializable
public data class CheckoutParams(
    public val checkout: Checkout,
)

@Serializable
public data class ErrorParams(
    public val error: ErrorResponse,
)
