name: Protocol

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      checks: write
      pull-requests: read
    defaults:
      run:
        working-directory: protocol
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js, pnpm, and install dependencies
        uses: ./.github/actions/setup
        with:
          node-version-file: protocol/package.json
          cache-dependency-path: protocol/pnpm-lock.yaml
          package-json-file: protocol/package.json
          working-directory: protocol

      - name: Test with coverage
        id: coverage_tests
        run: pnpm test --coverage

      - name: Record coverage
        if: ${{ !cancelled() }}
        uses: ./.github/actions/report-coverage
        with:
          platform: protocol
          report-path: protocol/coverage/coverage-summary.json
          report-directory: protocol/coverage
          outcome: ${{ steps.coverage_tests.outcome }}
