name: Swift — Run Package Tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package-tests:
    uses: ./.github/workflows/swift-test-workflow.yml
    with:
      test-path: ./Scripts/xcode_run test ShopifyCheckoutKit-Package
      job-name: Run Package Tests
      artifact-name: swift-package-tests-xcresult
      summarize-tests: true
