name: Swift — Build Sample Apps

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-samples:
    uses: ./.github/workflows/swift-test-workflow.yml
    with:
      test-path: ./Scripts/build_samples
      job-name: Build Sample Apps
