name: Swift — Build & Test Sample Apps

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test-samples:
    uses: ./.github/workflows/swift-test-workflow.yml
    with:
      test-path: ./Scripts/build_samples && ./Scripts/test_samples
      job-name: Build & Test Sample Apps
      setup-storefront-env: true
