name: Swift — Build Sample Apps

on:
  workflow_call:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/swift-test-workflow.yml
    with:
      test-path: ./Scripts/build_samples
