name: Web — Check License Headers

on:
  workflow_call:
  workflow_dispatch:

jobs:
  license:
    name: Verify license headers
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: platforms/web
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Ruby
        uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # v1.307.0
        with:
          ruby-version: '3.0'

      - name: Check license headers
        run: ./scripts/check_license_headers.rb
